language: nodejs

sudo: required

install:
  - npm install
  - npm i -g mocha
  - npm i -g typedoc

script:
  - npm test

before_install:
  - chmod +x build.sh 

after_success:
  - typedoc --out docs/